service: lambda-dlq-testing

custom:
   accountNumber: ${opt:account-number}

provider:
   name: aws
   runtime: nodejs8.10
   iamRoleStatements:
      -
         Effect: Allow
         Action:
            - sqs:SendMessage
         Resource:
            - 'arn:aws:sqs:us-east-1:${self:custom.accountNumber}:lambda-dlq-testing-SQSQueue'

functions:
   hello:
      handler: handler.hello

resources:
   Resources:
      HelloLambdaFunction:
         Type: 'AWS::Lambda::Function'
         Properties:
            DeadLetterConfig:
               TargetArn: 'arn:aws:sqs:us-east-1:${self:custom.accountNumber}:lambda-dlq-testing-SQSQueue'
      SNSTopic:
         Type: 'AWS::SNS::Topic'
         Properties:
            DisplayName: 'lambda-dlq-testing-SNSTopic'
            TopicName: 'lambda-dlq-testing-SNSTopic'
      SQSQueue:
         Type: 'AWS::SQS::Queue'
         Properties:
            QueueName: 'lambda-dlq-testing-SQSQueue'
